spring.application.name=airline-booking-app

spring.datasource.url=jdbc:mysql://localhost:3306/airlinedb
spring.datasource.username=root
spring.datasource.password=airline
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


jwtSecreteString=phegonairline123456789phegonairline123456789phegonairline123456789


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phegonshow@gmail.com
spring.mail.password=mlgw zygh btrv udhk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

frontendLoginUrl=http://localhost:3000/login
viewBookingUrl=http://localhost:3000/my-bookings